# Generated by Django 4.2.7 on 2024-01-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_comment_id_alter_post_id_alter_postimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
