# Generated by Django 4.2.7 on 2023-12-08 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('like_counts', models.IntegerField(default=0)),
                ('dislike_counts', models.IntegerField(default=0)),
                ('comment_counts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='users.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='users.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.profile')),
            ],
        ),
    ]
