# Generated by Django 4.2.7 on 2023-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_following',
            field=models.IntegerField(default=0),
        ),
    ]
