# Generated by Django 4.2.7 on 2023-12-08 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_counts', models.IntegerField(default=0)),
                ('dislike_counts', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='reply_dislikes', to='users.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='reply_likes', to='users.profile')),
            ],
        ),
    ]
