# Generated by Django 4.2.7 on 2023-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_counts',
            field=models.IntegerField(default=0),
        ),
    ]
