# Generated by Django 4.2.7 on 2023-12-04 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_postimage_post_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
