# Generated by Django 4.2.7 on 2023-12-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_comment_id_alter_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=None),
        ),
    ]
