# Generated by Django 4.2.7 on 2023-12-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='like_counts',
        ),
    ]
